const products = {
    "honey-lavender": {
        title: "Honey Lavender",
        slogan: "Soothing and great to start each day",
        productType: "box",
        price: "$12.00",
        imgFile: "honey-lavender-box.webp",
        bgColor: "#e9d8f4",
        btnBgColor: "#2c2592",
        btnFgColor: "#ffffff",
        teaColorTop: "#7b4290",
        teaColorFront: "#b781cc",
    },
    "raspberry-mint": {
        title: "Raspberry Mint",
        slogan: "Soothing and great to start each day",
        productType: "box",
        price: "$12.00",
        imgFile: "raspberry-mint-box.webp",
        bgColor: "#d3fae8",
        btnBgColor: "#d42406",
        btnFgColor: "#ffffff",
        teaColorTop: "#f41d1d",
        teaColorFront: "#ef3535",
    },
    "peach": {
        title: "Peach",
        slogan: "Soothing and great to start each day",
        productType: "box",
        price: "$12.00",
        imgFile: "peach-box.webp",
        bgColor: "#fff1dc",
        btnBgColor: "#bf5420",
        btnFgColor: "#ffffff",
        teaColorTop: "#ee9d3f",
        teaColorFront: "#f2a953",
    },
    "rose-lavender": {
        title: "Rose & Lavender",
        slogan: "Soothing and great to start each day",
        productType: "box",
        price: "$12.00",
        imgFile: "rose-lavender-box.webp",
        bgColor: "#d3eafa",
        btnBgColor: "#c01134",
        btnFgColor: "#ffffff",
        teaColorTop: "#df69d3",
        teaColorFront: "#e673db",
    },
    "pomegranate": {
        title: "Pomegranate",
        slogan: "Soothing and great to start each day",
        productType: "box",
        price: "$12.00",
        imgFile: "pomegranate-box.webp",
        bgColor: "#fad9d3",
        btnBgColor: "#7d2314",
        btnFgColor: "#ffffff",
        teaColorTop: "#c0392c",
        teaColorFront: "#ba453a",
    },
    "black-tea-lemon": {
        title: "Black Tea & Lemon",
        slogan: "Soothing and great to start each day",
        productType: "box",
        price: "$12.00",
        imgFile: "black-tea-lemon-box.webp",
        bgColor: "#faf3d3",
        btnBgColor: "#9a5e22",
        btnFgColor: "#ffffff",
        teaColorTop: "#815a0a",
        teaColorFront: "#946f23",
    },
    "tea-infuser-jar": {
        title: "Tea Infuser Jar",
        slogan: "Soothing and great to start each day",
        productType: "other",
        price: "$27.00",
        imgFile: "tea-infuser-jar.webp",
        bgColor: "#faf3d3",
        btnBgColor: "#9a5e22",
        btnFgColor: "#ffffff",
        teaColorTop: "n/a",
        teaColorFront: "n/a",
    },
    "tea-infuser-balls": {
        title: "Tea Infuser Balls",
        slogan: "Soothing and great to start each day",
        productType: "other",
        price: "$9.00",
        imgFile: "tea-infuser-ball.webp",
        bgColor: "#faf3d3",
        btnBgColor: "#9a5e22",
        btnFgColor: "#ffffff",
        teaColorTop: "n/a",
        teaColorFront: "n/a",
    },
    "honey-lavender-loose-leaf": {
        title: "Honey Lavender Loose Leaf",
        slogan: "Soothing and great to start each day",
        productType: "loose-leaf",
        price: "$25.00",
        imgFile: "honey-lavender-can.webp",
        bgColor: "#e9d8f4",
        btnBgColor: "#2c2592",
        btnFgColor: "#ffffff",
        teaColorTop: "#7b4290",
        teaColorFront: "#b781cc",
    },
    "raspberry-mint-loose-leaf": {
        title: "Raspberry Mint Loose Leaf",
        slogan: "Soothing and great to start each day",
        productType: "loose-leaf",
        price: "$25.00",
        imgFile: "raspberry-mint-can.webp",
        bgColor: "#d3fae8",
        btnBgColor: "#d42406",
        btnFgColor: "#ffffff",
        teaColorTop: "#f41d1d",
        teaColorFront: "#ef3535",
    }
}

export { products };
